[phases.setup]
nixPkgs = ["nodejs", "python311"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "npm install -g playwright",
  "playwright install --with-deps"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
