[build]
languages = ["python", "nodejs"]

[phases.setup]
nixPkgs = ["python311", "nodejs"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "npm install -g playwright",
  "playwright install --with-deps"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"

